postgres:
  dsn: postgres://root:gnsgnsgnsgnsg4225y25sxvbs@localhost:5431/irc_calcs?sslmode=disable

bots:
  channel: "#fidorus"
  nickname: calc-test
  addresses:
    - open.ircnet.net:6667
  encoding: koi8-r

logger:
  level: debug
  time:
    key: time
    layout: 2006-01-02T15:04:05.999999999Z07:00
  message:
    key: message
